### PR TITLE
Updated doring shapefile

### PR DESCRIPTION
**Pull request by jeromaerts**
In this PR, I added the new Doring catchment shapefile and changed the filenames to start with a capital letter.

### CODE REVIEW

**Comment by Peter9192** [comment]
What's this?
`Lorentz_Basin_Shapefiles/Doring/doring.qpj → Lorentz_Basin_Shapefiles/Doring/.nfs000000000f779a8700004146`

**Review by Peter9192 — CHANGES_REQUESTED** [review]
What's this?
`Lorentz_Basin_Shapefiles/Doring/doring.qpj → Lorentz_Basin_Shapefiles/Doring/.nfs000000000f779a8700004146`

and this:
`Lorentz_Basin_Shapefiles/Merrimack/merrimack.qpj → Lorentz_Basin_Shapefiles/Great_Kei/Great_Kei.qpj`

and this:
`Lorentz_Basin_Shapefiles/Merrimack/merrimack.shp → Lorentz_Basin_Shapefiles/Merrimack/.nfs000000000f779a4f00004147`

and this:
`Lorentz_Basin_Shapefiles/Meuse/meuse.qpj → Lorentz_Basin_Shapefiles/Merrimack/Merrimack.qpj`

and this:
`Lorentz_Basin_Shapefiles/Rhine/rhine.qpj → Lorentz_Basin_Shapefiles/Meuse/Meuse.qpj`

and this:
`Lorentz_Basin_Shapefiles/Savannah/savannah.qpj → Lorentz_Basin_Shapefiles/Rhine/Rhine.qpj`

It seems that something went wrong in renaming all the files. It seems to be systematic as well. The `.qpj` files seem to be renamed to the previous catchment in a loop or so.

Can you check again to see whether all filenames correspond with the file contents?

Also Merrimack.shp and Savannah.qpj have been changed. Is that correct?

**Comment by jeromaerts** [comment]
@Peter9192 I removed the .nfs000000000f779a8700004146 files (Cartesius systemfiles). I checked all the file names and contents and modified the catchments. I have tested them using QGIS on my local machine.

**Review by Peter9192 — APPROVED** [review]

**Comment by Peter9192** [comment]
One more thing: there's several places in which we read these shapefiles. We need to make sure to update the filenames in those places. Can you make an issue about that in the ERA5 comparison repo? I guess a PR is not necessary, since we can change the paths in some of other PRs we're currently working on

**Pull request merged**
